# arch/arm/plat-anyka/Makefile
#
# Copyright 2012 Anyka Microelectronics
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

# Core support for all Anyka SoCs

obj-y				+= l2.o
obj-y				+= rtc.o
obj-y				+= drv_module_lock.o
obj-y				+= l2_exebuf.o
obj-y				+= notify.o
obj-y				+= reg.o
