// Lang.h: interface for the CLang class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_LANG_H__7A3A98C3_478A_4921_AE17_55EB49099359__INCLUDED_)
#define AFX_LANG_H__7A3A98C3_478A_4921_AE17_55EB49099359__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000



#define   LANG_CHINA_ENGLISH_LEN        50   //提示的中英文长度不能超过50，否则会出现死机

enum
{
IDS_TITLE = 0,//标题
IDS_UPDATE_MODE,//升级模式

IDS_MENU_UPDATE,//升级
IDS_MENU_UPDATE_IMPORT,
IDS_MENU_UPDATE_EXPORT,
IDS_MENU_SETTING,
IDS_CONFIG_SETTING,
IDS_MENU_MODIFY_PASSWD,
IDS_MENU_VIEW,
IDS_MENU_LANGUAGE,//语言
IDS_MENU_COM_WINDOW,
IDS_MENU_TOOL,//工具
IDS_MENU_CREATIMAGE_TOOL,//制作镜像工具
IDS_SPI_IMAGE_MAKER,//spi镜像制作
IDS_BIN_READ_BACK,
IDS_MENU_CONFIG,
IDS_MENU_HELP,
IDS_MENU_ABOUT,

IDS_TOOLBAR_START,//状态
IDS_TOOLBAR_SETTING,//设置
IDS_TOOLBAR_IMPORT,//导入
IDS_TOOLBAR_EXPORT,//导出
IDS_TOOLBAR_FORMAT,//低格

IDS_MAINVIEW_STATUS_IMAGE,
IDS_MAINVIEW_NUMBER,
IDS_MAINVIEW_PROGRESS,
IDS_MAINVIEW_STATUS_TEXT,
IDS_MAINVIEW_TIMER,
IDS_MAINVIEW_SEQUENCE,
IDS_MAINVIEW_MAC_ADDR,
IDS_MAINVIEW_DEVICE,

IDS_MAINVIEW_CUR_NUM,//当前个数
IDS_MAINVIEW_CUR_USEFUL,//当前使用
IDS_MAINVIEW_CUR_PASS,//当前通过
IDS_MAINVIEW_TOTAL_PASS,//总通过
IDS_MAINVIEW_TOTAL_FAIL,//未通过
IDS_MAINVIEW_CLR_REC,
IDS_STATIC_STATE,
IDS_STATIC_NOW_UDISK,//usb
IDS_STATIC_UDISK_NUM,//u盘
IDS_AUTO_BURN,//自动烧录
IDS_UDISK_BURN,//u盘烧录
IDS_ONLINE_IMAGE_MAKE,//在线制作

IDS_USER_PRODUCER,//produce
IDS_USER_RESEACHER,
IDS_PASSWORD_TIP,
IDS_PASSWORD_USER_NAME,
IDS_PASSWORD_WORD,
IDS_PASSWORD_MODIFY_TITLE,
IDS_PASSWORD_USER,
IDS_PASSWORD_OLDWORD,
IDS_PASSWORD_NEWWORD,
IDS_PASSWORD_CONFIRM,
IDS_PASSWORD_ERROR,
IDS_PASSWORD_CONFIRM_ERROR,
IDS_PASSWORD_MODIFY_SUCCESS,


IDS_BURN_READY,
IDS_BURN_UDISK_UPDATE_READY,
IDS_BURN_START,
IDS_BURN_START_SET_RAMPARAM,
IDS_BURN_SET_RAMPARAM_FAIL,
IDS_BURN_START_SET_REGISTERS,
IDS_BURN_SET_REGISTERS_FAIL,
IDS_BURN_GET_REGISTERS_FAIL,
IDS_BURN_SET_REGISTERS_SUCCESS,
IDS_BURN_START_INIT_USB,
IDS_BURN_INIT_USB_FAIL,
IDS_BURN_COMPLETE,
IDS_BURN_START_DOWNLOAD_AND_TESTRAM,
IDS_BURN_DOWNLOAD_AND_TESTRAM_FAIL,
IDS_BURN_START_DOWNLOAD_PRODUCER,//
IDS_BURN_DOWNLOAD_PRODUCER_FAIL,//
IDS_BURN_DOWNLOAD_PRODUCER_USB_FAIL,//
IDS_BURN_DOWNLOAD_PRODUCER_TIMEOUT_FAIL,//
IDS_BURN_DOWNLOAD_PRODUCER_SUCESS,//
IDS_PARTTION_INFORMATION_IS_NULL,//
IDS_GET_MEDIUM_DATAINFO_FAIL,//
IDS_GET_FREE_BLOCK_FAIL,//
IDS_LOW_FORMAT_START,//
IDS_LOW_FORMAT_FAIL,
IDS_MALLOC_MEDIUM_FAIL,//
IDS_BURN_START_TEST,//
IDS_BURN_TEST_FAIL,
IDS_BURN_START_GET_NAND_CHIP_ID,//
IDS_BURN_GET_NAND_CHIP_ID_FAIL,
IDS_BURN_START_SET_NAND_PARAM,
IDS_BURN_SET_NAND_PARAM_FAIL,

IDS_BURN_START_GET_SPIFLASH_CHIP_ID,
IDS_BURN_GET_SPIFLASH_CHIP_ID_FAIL,
IDS_BURN_START_SET_SPIFLASH_PARAM,
IDS_BURN_SET_SPIFLASH_PARAM_FAIL,

IDS_BURN_START_ERASE,
IDS_BURN_ERASE_FAIL,
IDS_BURN_START_FORMAT,
IDS_BURN_FORMAT_FAIL,
IDS_BURN_START_DOWNLOAD_FILE,
IDS_BURN_DOWNLOAD_FILE_FAIL,
IDS_BURN_START_GET_AID,
IDS_BURN_GET_AID_FAIL,

IDS_GENERAL_PROJECT_NAME,
IDS_GENERAL_CHANNEL_NUM,
IDS_PLANFORM_TYPE,
IDS_GENERAL_OPEN_COM,
IDS_GENERAL_COM_NUM,
IDS_GENERAL_COM_BASE,
IDS_GENERAL_COM_BAUDRATE,
IDS_GENERAL_CONFIG_CMDLINE,
IDS_GENERAL_CMD_ADDR,
IDS_GENERAL_CMD_DATA,

IDS_GENERAL_BURN_MAC_ADDR,
IDS_GENERAL_FORCE_WRITE_MAC_ADDR,//
IDS_MACADDR_RESET,
IDS_GENERAL_MAC_START_ADDR,//mac
IDS_GENERAL_MAC_END_ADDR,//mac
IDS_GENERAL_BURN_SEQUNCE,//序列号
IDS_GENERAL_FORCE_WRITE_SEQUNCE,//强制写
IDS_SEQUENCE_ADDR_RESET,
IDS_GENERAL_SEQUNCE_START,
IDS_GENERAL_SEQUNCE_END,
IDS_GENERAL_MAC_START_NAME,
IDS_GENERAL_MAC_END_NAME,
IDS_GENERAL_SERIAL_START_NAME,
IDS_GENERAL_SERIAL_END_NAME,

IDS_GENERAL_EXPLORER,
IDS_GENERAL_PATH_PRODUCER,
IDS_GENERAL_PATH_NANDBOOT,
IDS_GENERAL_PATH_NANDBOOT_NEW,
IDS_GENERAL_PATH_BIOS,

IDS_DOWNLOAD_U_DISK,
IDS_DOWNLOAD_NANDFLASH,
IDS_DOWNLOAD_MTD,
IDS_DOWNLOAD_NUMBER,
IDS_DOWNLOAD_COMPARE,
IDS_DOWNLOAD_YES,
IDS_DOWNLOAD_NO,
IDS_DOWNLOAD_PC_PATH,
IDS_DOWNLOAD_FILE,
IDS_DOWNLOAD_DIR,
IDS_DOWNLOAD_UDISK_PATH,
IDS_DOWNLOAD_START_ADDR,
IDS_DOWNLOAD_END_ADDR,
IDS_DOWNLOAD_BACKUP_START_ADDR,
IDS_DOWNLOAD_BACKUP_END_ADDR,
IDS_DOWNLOAD_DISK_NAME,

IDS_LINK_ADDRESS,
IDS_FILE_NAME,
IDS_DOWNLOAD_BACKUP,
IDS_BACKUP_YES,
IDS_BACKUP_NO,
IDS_SETBIN_EXCTERNSIZE,

IDS_HARDWARE_CHIP_TYPE,
IDS_HARDWARE_USB2,
IDS_HARDWARE_PLLFREP,
IDS_HARDWARE_GET_AID,
IDS_HARDWARE_UPDATE_MODE,
//IDS_HARDWARE_AUTO_DOWNLAOD,
//IDS_HARDWARE_CHIP_CLK,
IDS_STATIC_SD_RAM,
IDS_GROUP_GPIO,
IDS_STATIC_BURN_MODE,
IDS_STATIC_BURNED,
IDS_BUTTON_IMPORT_RAM_CONFIG,//
IDS_BUTTON_EXPORT_RAM_CONFIG,//
IDS_STATIC_RAM_ROW,
IDS_STATIC_RAM_COLUMN,
IDS_HARDWARE_UBOOT,
IDS_HARDWARE_POWER_OFF_GPIO,
IDS_HARDWARE_BIOS_START_ADDR,//
IDS_HARDWARE_FS_RESERVER_BLK,//
IDS_HARDWARE_RAM_TYPE,//
IDS_HARDWARE_RAM_SIZE,//
IDS_HARDWARE_RAM_BANK,//
IDS_HARDWARE_RAM_ROW_LEN,//
IDS_HARDWARE_RAM_COL_ADDR,//
IDS_HARDWARE_NAND_CHIP_SEL,//
IDS_HARDWARE_NAND_CHIP_MAN,//
IDS_HARDWARE_NAND_CHIP0,//
IDS_HARDWARE_NAND_CHIP1,//
IDS_HARDWARE_NAND_CHIP2,
IDS_HARDWARE_NAND_CHIP3,
IDS_HARDWARE_NAND_CHIP_ALL,
IDS_HARDWARE_INIT_USB,
IDS_HARDWARE_PLUG_GPIO,
IDS_HARDWARE_WRITE_REGISTERS,
IDS_HARDWARE_REGISTER,
IDS_HARDWARE_BIT,

IDS_FORMAT_LIST,
IDS_FORMAT_NUMBER,
IDS_FORMAT_DISK_SYMBOL,//
IDS_FORMAT_USER_DISK,//
IDS_FORMAT_DISK_INFOR,//
IDS_FORMAT_DISK_ATTR,//
IDS_FORMAT_DISK_SIZE,//
IDS_FORMAT_DISK_VOLUME,//
IDS_FORMAT_FS_RESV,//
IDS_FORMAT_NONFS_RESV,

IDS_NAND_LIST,
IDS_SPINAND_LIST,
IDS_SPI_LIST,

IDS_MODULEBURN_START,
IDS_MODULEBURN_FAIL,//
IDS_MODULEBURN_DEVICE_SYNCHRONIZED,//
IDS_MODULEBURN_BOOT_FAIL,//
IDS_MODULEBURN_DL_FLS_START,//
IDS_MODULEBURN_DL_EEP_START,//
IDS_MODULEBURN_DL_FLS_FAIL,
IDS_MODULEBURN_DL_EEP_FAIL,

IDS_BASEBAND_DOWNLOAD_MODE,
IDS_BASEBAND_DOWNLOAD_AK_ONLY,//
IDS_BASEBAND_DOWNLOAD_IFX_ONLY,//
IDS_BASEBAND_DOWNLOAD_BOTH,
IDS_BASEBAND_BURN_SETTING,//
IDS_BASEBAND_BAUDRATE,
IDS_BASEBAND_DOWNLOAD_FLS,
IDS_BASEBAND_DOWNLOAD_EEP,
IDS_BASEBAND_BROWSE,
IDS_BASEBAND_GPIO_SETTING,
IDS_BASEBAND_GPIO_SETTING_FAIL,
IDS_SET_PARAM_TO_PRODUCER_FAIL,

IDS_DOWNLOAD_BIN_START,
IDS_DOWNLOAD_BIN_FAIL,
IDS_DOWNLOAD_IMG_START,
IDS_DOWNLOAD_IMG_FAIL,
IDS_DOWNLOAD_BOOT_START,
IDS_DOWNLOAD_BOOT_FAIL,

IDS_WRITE_MAC_ADDR_ASA_START,
IDS_WRITE_MAC_ADDR_ASA_FAIL,
IDS_WRITE_SERIAL_ADDR_ASA_START,
IDS_WRITE_SERIAL_ADDR_ASA_FAIL,

IDS_BURN_START_DOWNLOAD_CHANGE_CLK,
IDS_BURN_DOWNLOAD_CHANGE_CLK_FAIL,//
IDS_BURN_DOWNLOAD_CHANGE_CLK_TIMEOUT_FAIL,//
IDS_BURN_DOWNLOAD_CHANGE_CLK_USB_FAIL,//

IDS_SET_MODE_START,
IDS_SET_MODE_FAIL,
IDS_SET_ERASEMODE_START,
IDS_SET_ERASEMODE_FAIL,
IDS_SET_NAND_PARA_START,
IDS_SET_NAND_PARA_FAIL,
IDS_SET_SEC_AREA_START,
IDS_SET_SEC_AREA_FAIL,
IDS_BIN_UPLOAD_FAIL,
IDS_GET_BAD_BLOCK_FAIL,

IDS_BURN_MAC_ADDR_READ,            
IDS_BURN_MAC_ADDR_READ_ERROR,   
IDS_BURN_SERIAL_ADDR_READ,       
IDS_BURN_SERIAL_ADDR_READ_ERROR,  

IDS_BURN_MAC_ADDR_COMPARE,   
IDS_BURN_MAC_ADDR_FAIL,  
IDS_BURN_SERIAL_ADDR_COMPARE,  
IDS_BURN_SERIAL_ADDR_FAIL, 

IDS_SET_RESV_AREA_START,
IDS_SET_RESV_AREA_FAIL,
IDS_CREATE_PARTITION_START,
IDS_CREATE_PARTITION_FAIL,
IDS_CLOSE_START,
IDS_CLOSE_FAIL,

IDS_INPUTNUM_IS16NUM,//
IDS_MACADDR_FORMAT,//
IDS_MACADDR_START_HIGHLEN_8,//
IDS_MACADDR_START_LOWLEN_8,//
IDS_MACADDR_END_HIGHLEN_8,///
IDS_MACADDR_END_LOWLEN_8,//
IDS_STRING_NUM_TYPE,//
IDS_MACADDR_START_END_HIGH_DIFFRENT,//
IDS_MACADDR_START_END_LOW_MOER,//
IDS_SERIALADDR_START_HIGHLEN_10,//
IDS_SERIALADDR_START_LOWLEN_6,//
IDS_SERIALADDR_END_HIGHLEN_10,//
IDS_SERIALADDR_END_LOWLEN_6,//
IDS_SERIALADDR_START_END_HIGH_DIFFRENT,//
IDS_SERIALADDR_START_END_LOW_MOER,//
IDS_MACADDR_RESET_SUCCEED,//
IDS_SEQUENCE_RESET_SUCCEED,//

IDS_SET_CHANNELID,
IDS_CHANNELID_FAIL,	

IDS_MAKE_IMAGE_TITLE,
IDS_SOURCE_FOLDER,
IDS_DEST_FOLDER,
IDS_BROWSE_SOURCE_FOLDER,//BROWSE_SOURCE
IDS_BROWSE_DEST_FOLDER,//BROWSE_DEST
IDS_IMAGE_FILE_NAME,//IMAGE_FILE
IDS_TOTAL_CAPACITY,//TOTAL_CAPACITY
IDS_PAGE_SIZE,//PAGE_SIZE
IDS_SECTOR_SIZE,//SECTOR_SIZE
IDS_MAKE_INFORMATION,//MAKE_INFORMATION
IDS_READY_MAKE,//
IDS_MAKING,//
IDS_MAKE_BEGIN,//
IDS_MAKE_END,
IDS_SUSSCCE,
IDS_FAIL,
IDS_GET_FOLDER_INFO,
IDS_GET_FOLDER_INFO_FAIL,
IDS_TOTAL_CAPACITY_NO_ENOUGH,
IDS_PARAM_ERROR,

IDS_SOURCE_FOLDER_EMPTY,//SOURCE_FOLDER
IDS_DEST_FOLDER_EMPTY,//DEST_FOLDER
IDS_IMAGE_NAME_EMPTY,//IMAGE_NAME
IDS_CAPACITY_SIZE_EMPTY,//CAPACITY_SIZE
IDS_SECTOR_SIZE_EMPTY,//SECTOR_SIZE
IDS_PAGE_SIZE_EMPTY,//PAGE_SIZE


IDS_SET_NAND_GPIOCE_FAIL,//
IDS_DOWNLOAD_CHANNELID_FAIL,  //
IDS_SET_COMMODE_FAIL,   //
IDS_DOWNLOAD_COMADDR_FAIL,	//

IDS_START_IMAGE_CREATE,//镜像制作
IDS_IMAGE_CREATE_SUCCESS,     //镜像创建成功
IDS_IMAGE_CREATE_FAIL, //失败
IDS_IMAGE_CREATE_RESET,//reset

IDS_CLOSE_OR_NO,

IDS_CHECK_EXPORT_DIALOG,
IDS_MSG_UPD_IMPORT_SUCCESS,
IDS_MSG_UPD_IMPORT_FAIL,
IDS_MSG_WAIT,
IDS_MSG_UPD_EXPORT_SUCCESS,
IDS_MSG_UPD_EXPORT_FAIL,

IDS_PHYSICAL_FORMAT,
IDS_SPI_IMAGE_TITLE,
IDS_STATIC_SPI_CHOOSE,//
IDS_STATIC_SPINAME,//
IDS_NO_SPI,//
IDS_HELP_FILE_ERROR,//

IDS_BUTTON_LOW_FORMAT,//
IDS_OK,
IDS_CANCEL,//
IDS_VOLUME_LABLE,//

IDS_MACADDR_HIGH_ONE,//
IDS_MACADDR_HIGH_ZERO,//
IDS_GET_HIGHID,//
IDS_GET_ALL_FREE_BLOCK,//
IDS_MEDIUM_CAPACITY_FAIL,
//IDS_MEDIUM_CAPACITY_CHECK_FAIL,
IDS_MEDIUM_CAPACITY_CHECK,
IDS_BIN_UPLOAD_COMPLETE,
IDS_BIN_UPLOAD,
IDS_SPIFLASH_UPLOAD_COMPLETE,
IDS_SPIFLASH_UPLAOD_FAIL,
IDS_SPIFLASH_UPLOAD,
IDS_UPLOAD_SPIFLASH_START,

IDS_MAX,
};

class CLang  
{
public:
	CLang();
	virtual ~CLang();

protected:
	TCHAR *m_stringAlloc;//
	UINT *m_offsetAlloc;//

public:
	UINT m_langCount;//
	UINT m_activeLang;//
	CString m_langName[20];//

public:
	BOOL Init(CString langName);//初始化
	CString GetString(UINT strID);//获取字符串

	BOOL WriteString();//写字符串
	BOOL ChangeLang(UINT langID);//改变语言

protected:
	BOOL LoadDefaultString(BOOL bCN);//下载默认的字符串
	BOOL LoadStringFromFile(CString strPath);

	UINT ScanLang(CString dirPath);
};

#endif // !defined(AFX_LANG_H__7A3A98C3_478A_4921_AE17_55EB49099359__INCLUDED_)
