//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BurnTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_BURNTOTYPE                  129
#define IDR_TLB_BURN                    131
#define IDD_CONFIG                      133
#define IDD_CFG_GENERAL                 134
#define IDI_ICON_LEFT                   136
#define IDI_ICON_RIGHT                  137
#define IDI_ICON_PREFERENCE             138
#define IDD_CFG_DOWNLOAD                139
#define IDD_CFG_HARDWARE                142
#define IDD_CFG_NANDFLASH               144
#define IDD_CFG_FORMAT                  145
#define IDI_ICON_FACE_RED               151
#define IDI_ICON_FACE_GREEN             152
#define IDI_ICON_FACE_GRAY              153
#define IDI_ICON_FACE_YELLOW            154
#define IDD_DLG_CHANGE_PASSWORD         155
#define IDD_DLG_PASSWORD                156
#define IDI_ICON_KEY                    163
#define IDD_CFG_BASEBAND                164
#define IDD_CFG_SPIFLASH                165
#define IDD_DIALOG1                     166
#define IDD_BAR_BURN_INFO               166
#define IDD_DLG_IMAGE_CREATE            167
#define IDD_DLG_CHECK_EXPORT            172
#define IDI_ICON_FORMAT                 173
#define IDI_ICON_EXPORT                 174
#define IDI_ICON_IMPORT                 175
#define IDD_DLG_SPI_IMAGE               176
#define IDD_CFG_SPINANDFLASH            177
#define IDC_EDIT_FIRST_COM              1000
#define IDC_EDIT_COM_BASE               1000
#define IDC_EDIT_PROJECT_NAME           1003
#define IDC_EDIT_COM_NUM                1004
#define IDC_EDIT_DEVICE_NUM             1005
#define IDC_EDIT_PATH_PRODUCER          1006
#define IDC_EDIT_USB_REGISTER_BIT       1006
#define IDC_EDITPATH_NANDBOOT           1007
#define IDC_EDIT_PATH_NANDBOOT          1007
#define IDC_EDIT_POWER_OFF_GPIO         1007
#define IDC_EDIT_PATH_BIOS              1008
#define IDC_EDIT_FS_RESERVE             1008
#define IDC_EDIT_PATH_NANDBOOT_NEW      1008
#define IDC_EDIT_BIOS_ADDRESS           1009
#define IDC_LIST_DOWNLOAD_UDISK         1011
#define IDC_LIST_DOWNLOAD_NAND          1012
#define IDC_BTN_BROWSE_PRODUCER         1013
#define IDC_CHECK_OPEN_COM              1014
#define IDC_EDIT_BAUDRATE               1015
#define IDC_BTN_BROWSE_NANDBOOT         1016
#define IDC_BTN_BROWSE_BIOS             1017
#define IDC_BTN_BROWSE_NANDBOOT_NEW     1017
#define IDC_STATIC_PROJECT_NAME         1018
#define IDC_STATIC_DEVICE_NUM           1019
#define IDC_STATIC_COM                  1020
#define IDC_STATIC_POWER_OFF_GPIO       1020
#define IDC_STATIC_COM_NUM              1021
#define IDC_STATIC_FS_RESERVE           1021
#define IDC_STATIC_FIRST_COM            1022
#define IDC_STATIC_COM_BASE             1022
#define IDC_STATIC_BIOS_ADDRESS         1022
#define IDC_STATIC_BAUDRATE             1023
#define IDC_STATIC_PATH                 1024
#define IDC_STATIC_PATH_PRODUCER        1025
#define IDC_STATIC_PATH_NANDBOOT        1026
#define IDC_STATIC_PATH_BIOS            1027
#define IDC_STATIC_PATH_NANDBOOT_NEW    1027
#define IDC_STATIC_CHIP_TYPE            1028
#define IDC_CHECK_USB_BOOT              1029
#define IDC_CHECK_AUTO_DOWNLOAD         1030
#define IDC_CHECK_CHIP_SELECT1          1031
#define IDC_CHECK_CHIP_SELECT2          1032
#define IDC_CHIP_TYPE_LIST              1033
#define IDC_RADIO_GPIO                  1034
#define IDC_RADIO_REGISTER              1035
#define IDC_RADIO_DEFINE                1036
#define IDC_STATIC_REGISTER             1037
#define IDC_STATIC_BIT                  1038
#define IDC_STATIC_RAM_TYPE             1039
#define IDC_RAM_TYPE_LIST               1040
#define IDC_STATIC_RAM_SIZE             1041
#define IDC_RAM_SIZE_LIST               1042
#define IDC_RAM_ROW_LIST                1043
#define IDC_STATIC_RAM_ROW              1044
#define IDC_RAM_COLUMN_LIST             1045
#define IDC_STATIC_RAM_COLUMN           1046
#define IDC_RAM_BANK_LIST               1047
#define IDC_STATIC_RAM_BANK             1048
#define IDC_RADIO_LOOP                  1049
#define IDC_CHECK_CHIP_SELECT3          1050
#define IDC_CHECK_CHIP_SELECT0          1051
#define IDC_STATIC_UDISK                1052
#define IDC_CHECK_PIN_SELECT4           1052
#define IDC_CHECK_GPIO_PIN_SELECT       1052
#define IDC_STATIC_NANDFLASH            1053
#define IDC_LIST_NANDFLASH_PARAM        1054
#define IDC_LIST_FS_DISK_FORMAT         1056
#define IDC_EDIT_USB_GPIO               1057
#define IDC_EDIT_USB_REGISTER           1058
#define IDC_STATIC_INIT_USB             1062
#define IDC_GROUP_CHIP_SELECT           1063
#define IDC_GROUP_GPIO                  1063
#define IDC_STATIC_SYS_FREQUENCY        1064
#define IDC_STATIC_SD_RAM               1064
#define IDC_EDIT_SYS_FREQUENCY          1065
#define IDC_STATIC_BURN_MODE            1065
#define IDC_STATIC_VERSION              1069
#define IDC_EDIT_OLD_PASSWORD           1070
#define IDC_STATIC_OLD_PASSWORD         1071
#define IDC_STATIC_ENTER_PASSWORD       1072
#define IDC_EDIT_ENTER_PASSWORD         1073
#define IDC_EDIT_NEW_PASSWORD           1074
#define IDC_STATIC_USER_ID              1074
#define IDC_STATIC_NEW_PASSWORD         1075
#define IDC_USER_ID_TYPE_LIST           1075
#define IDC_EDIT_CONFIRM_PASSWORD       1076
#define IDC_STATIC_CONFIRM_PASSWORD     1077
#define IDC_STATIC_USER_ID_CHG          1078
#define IDC_USER_ID_TYPE_LIST_CHG       1079
#define IDC_STATIC_DOWNLOAD_UDISK       1082
#define IDC_STATIC_DOWNLOAD_NAND        1083
#define IDC_STATIC_FS_FORMAT            1084
#define IDC_STATIC_NAND_LIST            1085
#define IDC_STATIC_PASSWORD_TIP         1086
#define IDC_BTN_PASSWD_CANCEL           1087
#define IDC_STATIC_CORP                 1088
#define IDC_CHECK_USB2                  1089
#define IDC_CHECK_PLLFREP               1090
#define IDC_CHECK_UPDATE                1091
#define IDC_STATIC_NONFS_RESV           1092
#define IDC_EDIT_NONFS_RESV             1093
#define IDC_STATIC_DOWNLOAD_MTD         1094
#define IDC_LIST_DOWNLOAD_MTD           1095
#define IDC_CHECK_GET_AID               1095
#define IDC_RADIO_MCP_MODE              1096
#define IDC_RADIO_SDRAM_MODE            1097
#define IDC_RADIO_DOWNLOAD_AK           1098
#define IDC_RADIO_DOWNLOAD_INFINEON     1099
#define IDC_RADIO_DOWNLOAD_BOTH         1100
#define IDC_COMBO_MOUDLE_BURN_BUADRATE  1101
#define IDC_CHECK_DOWNLOAD_FLS          1102
#define IDC_CHECK_DOWNLOAD_EEP          1103
#define IDC_EDIT_PATH_EEP               1104
#define IDC_EDIT_PATH_FLS               1105
#define IDC_BTN_BROWSE_FLS              1106
#define IDC_BTN_BROWSE_EEP              1107
#define IDC_EDIT_GPIO_DTR               1109
#define IDC_EDIT_GPIO_MODULE_IGT        1110
#define IDC_EDIT_GPIO_MODULE_RESET      1111
#define IDC_STATIC_GPIO_DTR             1112
#define IDC_STATIC_GPIO_MODULE_IGT      1113
#define IDC_STATIC_GPIO_MODULE_RESET    1114
#define IDC_STATIC_MODULE_GPIO_SETTING  1115
#define IDC_STATIC_DOWNLOAD_MODE        1116
#define IDC_STATIC_MODULE_BURN_SETTING  1117
#define IDC_STATIC_MODULE_BURN_BAUDRATE 1118
#define IDC_RADIO_NANDFLASH             1120
#define IDC_RADIO_BURN_UPDATE           1121
#define IDC_RADIO_SPI_NANDFLASH         1121
#define IDC_RADIO_DEBUG                 1122
#define IDC_RADIO_SFLASH                1123
#define IDC_RADIO_DDR_MODE              1124
#define IDC_EDIT_FREQ                   1125
#define IDC_RADIO_BURN_SD               1126
#define IDC_EDIT_PROD_RUN_ADDR          1126
#define IDC_RADIO_SD                    1126
#define IDC_RADIO_DDR2_MODE             1127
#define IDC_RADIO_DDR2_16_MODE          1127
#define IDC_RADIO_DDR2_32_MODE          1128
#define IDC_RADIO_BURN_SD_UPDATE        1129
#define IDC_EDIT_GPIO_CE2               1130
#define IDC_EDIT_GPIO_CE3               1131
#define IDC_RADIO_DDR_MODE32            1132
#define IDC_CHK_CONFIG_CMDLINE          1133
#define IDC_EDIT_GPIO_PIN               1133
#define IDC_RADIO_JTAG                  1134
#define IDC_EDIT_CMDLINE_ADDR           1135
#define IDC_EDIT_CMDLINE_DATA           1136
#define IDC_EDIT_CMDLINE_ADDR2          1137
#define IDC_LIST_SPIFLASH_PARAM         1140
#define IDC_BUTTON_IMPORT_RAM_CONFIG    1141
#define IDC_BUTTON_EXPORT_RAM_CONFIG    1142
#define IDC_CHECK_UDISK_UPDATE          1143
#define IDC_GERNERAL_CMD_ADDR           1145
#define IDC_GERNERAL_CMD_DATA           1146
#define IDC_STATIC_SPI_LIST             1147
#define IDC_STATIC_CUR_NUM              1148
#define IDC_CUR_NUM                     1149
#define IDC_CUR_PASS                    1150
#define IDC_TOTAL_NUM                   1150
#define IDC_CUR_UDISK                   1151
#define IDC_EDIT5                       1153
#define IDC_TOTAL_PASS                  1153
#define IDC_EDIT_SEQUENCE_START_ADDR_LOW 1153
#define IDC_STATIC_CUR_PASS             1154
#define IDC_STATIC_TOTAL_NUM            1154
#define IDC_STATIC_CUR_UDISK            1155
#define IDC_TOTAL_FAIL                  1155
#define IDC_STATIC_CUR_USEFUL           1156
#define IDC_CUR_USEFUL                  1157
#define IDC_STATIC_TOTAL_PASS           1158
#define IDC_BUTTON_CLR_REC              1159
#define IDC_STATIC_TOTAL_FAIL           1160
#define IDC_BURNED_NONE                 1164
#define IDC_BURNED_RESET                1165
#define IDC_BURNED_POWER_OFF            1166
#define IDC_BURNED_GPIO                 1167
#define IDC_BURNED_RTC_WAKUP            1168
#define IDC_EDIT1                       1169
#define IDC_GPIO_PIN_NUM                1169
#define IDC_EVENT_TIME                  1169
#define IDC_EDIT_SOURCE_FOLDER          1169
#define IDC_EDIT_CHECK_STRING           1169
#define IDC_EDIT_UDISK_NUM              1169
#define IDC_BURNED_LVH                  1178
#define IDC_BURNED_LVL                  1179
#define IDC_GPIO_PULLUP_EN              1181
#define IDC_BURNED_PULLUP               1182
#define IDC_BURNED_PULLDOWN             1183
#define IDC_BURNED_RTC_LVH              1184
#define IDC_BURNED_RTC_LVL              1185
#define IDC_GPIO_PULLDOWN_EN            1186
#define IDC_STATIC_CHIP_SELECT          1190
#define IDC_COMBO_CHIP_SEL              1191
#define IDC_CHECK_MAC_ADDR              1194
#define IDC_CHECK_SEQUENCE_ADDR         1195
#define IDC_CHECK_FORCE_WRITE_MAC_ADDR  1203
#define IDC_CHECK_FORCE_WRITE_SEQUENCE_ADDR 1204
#define IDC_EDIT_SEQUENCE_START_ADDR_HIGH 1205
#define IDC_EDIT_MAC_START_ADDR_HIGH    1206
#define IDC_EDIT_MAC_START_ADDR_LOW     1207
#define IDC_EDIT_MAC_END_ADDR_HIGH      1208
#define IDC_EDIT_MAC_END_ADDR_LOW       1209
#define IDC_EDIT_SEQUENCE_END_ADDR_HIGH 1210
#define IDC_EDIT_SEQUENCE_END_ADDR_LOW  1211
#define IDC_STATIC_MAC_START_ADDR       1217
#define IDC_STATIC_MAC_END_ADDR         1218
#define IDC_STATIC_SEQUENCE_START       1219
#define IDC_STATIC_SEQUENCE_END         1220
#define IDC_EDIT2                       1222
#define IDC_EDIT_DEST_FOLDER            1222
#define IDC_EDIT_PID                    1222
#define IDC_EDIT_UDISK                  1222
#define IDC_BUTTON_SOURCE_BROWSER       1223
#define IDC_BUTTON_DEST_BROWSER         1224
#define IDC_STATIC_SOURCE_FOLDER        1227
#define IDC_STATIC_DEST_FOLDER          1228
#define IDC_EDIT_IMAGE_NAME             1229
#define IDC_EDIT_CAPACITY               1230
#define IDC_COMBO_PAGESIZE              1233
#define IDC_STATIC_IMAGE_NAME           1235
#define IDC_STATIC_CAPACITY             1236
#define IDC_STATIC_SECTORSIZE           1237
#define IDCREATE                        1239
#define IDC_STATIC_USED_TIME            1242
#define IDC_MAKE_INFORMATION            1243
#define IDC_CURENT_INFO                 1244
#define IDC_PROGRESS_MAKING             1245
#define IDC_STATIC_PAGESIZE             1247
#define IDC_EDIT_SECTORSIZE             1248
#define IDC_STATIC_PROG_TIME            1249
#define IDC_RADIO_DDR_16_MOBILE         1250
#define IDC_RADIO_DDR_32_MOBILE         1251
#define IDC_COMBO_PALNFORM_TYPE         1264
#define IDC_PLANFORM_TYPE               1265
#define IDC_CHECK_ONLINE_IMAGE_MAKE     1266
#define IDC_STATIC_MAC_END_NAME         1267
#define IDC_STATIC_MAC_START_NAME       1268
#define IDC_STATIC_SERIAL_START_NAME    1269
#define IDC_STATIC_SERIAL_END_NAME      1270
#define IDC_MACADDR_RESET               1271
#define IDC_SEQUENCE_ADDR_RESET         1272
#define IDC_STATIC_CE2_GPIO             1274
#define IDC_STATIC_DDR_Freq             1275
#define IDC_STATIC_Mhz                  1276
#define IDC_STATIC_CE3_GPIO             1277
#define IDC_STATIC_0x                   1278
#define IDC_STATIC_k1                   1279
#define IDC_STATIC_k2                   1280
#define IDC_STATIC_L1                   1281
#define IDC_STATIC_L2                   1282
#define IDC_STATIC_a1                   1283
#define IDC_STATIC_a2                   1284
#define IDC_STATIC_a3                   1285
#define IDC_STATIC_BURNED               1286
#define IDC_CHECK_AUTO_BURN             1290
#define IDC_STATIC_STATE                1291
#define IDC_STATIC_SPI_CHOOSE           1292
#define IDC_STATIC_SPINAME              1294
#define IDC_STATIC_SPI_ICON             1296
#define IDC_COMBO_SPL_TYPE_LIST         1297
#define IDC_BUTTON_LOW_FORMAT           1298
#define IDC_CHECK_UDISK_BURN            1300
#define IDC_STATIC_NOW_UDISK            1301
#define IDC_EDIT_VID                    1302
#define IDC_STATIC_PID                  1303
#define IDC_STATIC_VID                  1304
#define IDC_UPDATESELF                  1305
#define IDC_TEST_RAM                    1306
#define IDC_STATIC_SPI_NANDFLSH_LIST    1306
#define IDC_LIST_SPINANDFLASH_PARAM     1307
#define ID_TBTN_START                   32771
#define ID_TBTN_SETTING                 32772
#define ID_VIEW_COM                     32773
#define ID_SETTING_CHANGE_PASSWD        32776
#define ID_LANG_CHINESE                 32777
#define ID_LANG_ENGLISH                 32778
#define ID_APP_HELP                     32779
#define ID_TOOL_IMAGE_MAKER             32780
#define ID_MENU_CONFIG0                 32782
#define ID_UPDATE_IMPORT                32789
#define ID_UPDATE_EXPORT                32790
#define ID_TBTN_IMPORT                  32791
#define ID_TBTN_EXPORT                  32792
#define ID_TBTN_FORMAT                  32793
#define ID_SPI_IMAGE_MAKER              32794
#define ID_BIN_READ_BACK                32795
#define ID_CONFIG_SETTING               32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1308
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
