LOCAL_SRC_FILES := 	key.c 
export PATH := /home/user/videorec/compiler/arm-2009q3/bin:$(PATH)

LOCAL_MODULE := key

PREFIX := arm-none-linux-gnueabi-

LOCAL_SHARED_LIBRARIES 	:= pthread
LOCAL_C_INCLUDES 		:= 

LOCAL_LDFLAGS 			:= 

include exec_rules.mk
