
LOCAL_SRC_CFILES := \
					httpclient.c
LOCAL_SRC_CXXFILES := 

LOCAL_MODULE := httpclient

PREFIX := arm-none-linux-gnueabi-

#链接时指定的libs所在目录
LOCAL_SHARED_LIBRARIES := 
#编译时指定的要使用的外部头文件目录
LOCAL_C_INCLUDES := 
#链接时指定要链接的lib.
LOCAL_LDFLAGS := 
				
include exec_rules.mk
