LOCAL_SRC_CFILES := 	inisetting.c uart.c tpoll.c  
export PATH := /home/user/videorec/compiler/arm-2009q3/bin:$(PATH)
#USE_CPP := 1
LOCAL_MODULE := tpolld

PREFIX := arm-none-linux-gnueabi-

LOCAL_SHARED_LIBRARIES 	:= iniparser pthread 
LOCAL_C_INCLUDES 		:= 

LOCAL_LDFLAGS 			:= -L./

include exec_rules.mk
