//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ISPControl.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ISPCONTROL_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_PREVIEW              129
#define IDD_DIALOG_Enable               130
#define IDD_DIALOG_BB                   131
#define IDD_DIALOG_LENS                 132
#define IDD_DIALOG_DEMOSAIC             133
#define IDD_DIALOG_FILTER               134
#define IDD_DIALOG_WB                   135
#define IDD_DIALOG_COLOR_CORRECT        136
#define IDD_DIALOG_GAMMA                137
#define IDD_DIALOG_SATURATION           138
#define IDD_DIALOG_BRI_ENHANCE          139
#define IDD_DIALOG_SPECIAL_EFFECT       140
#define IDD_DIALOG_AWB                  141
#define IDR_MENU1                       142
#define IDD_DIALOG_REGISTER             143
#define IDD_DIALOG_SHOW_RGB_AVG         144
#define IDR_MENU2                       145
#define IDC_TAB1                        1000
#define IDC_TREE1                       1001
#define IDC_BUTTON1                     1002
#define IDC_BUTTON2                     1003
#define IDC_CHECK_BB                    1003
#define IDC_BUTTON3                     1004
#define IDC_CHECK_LENS_ADJUST           1004
#define IDC_SLIDER_R_OFFSET             1004
#define IDC_CHECK_DEMOSAIC              1005
#define IDC_SLIDER_G_OFFSET             1005
#define IDC_SLIDER_C12                  1005
#define IDC_BUTTON4                     1005
#define IDC_CHECK_RGB_FILTER            1006
#define IDC_SLIDER_B_OFFSET             1006
#define IDC_SLIDER_C13                  1006
#define IDC_CHECK_UV_FILTER             1007
#define IDC_CHECK_BB_ENABLE             1007
#define IDC_SLIDER_C21                  1007
#define IDC_CHECK_DEFECT_PIXEL          1008
#define IDC_STATIC_R                    1008
#define IDC_SLIDER_C22                  1008
#define IDC_CHECK_WB                    1009
#define IDC_STATIC_RVALUE               1009
#define IDC_SLIDER_C23                  1009
#define IDC_CHECK_AWB                   1010
#define IDC_STATIC_G                    1010
#define IDC_CHECK_LENS                  1010
#define IDC_SLIDER_C31                  1010
#define IDC_CHECK_CCORRECT              1011
#define IDC_STATIC_GVALUE               1011
#define IDC_SLIDER_ILOW                 1011
#define IDC_EDIT_XREF                   1011
#define IDC_CHECK_GAMMA                 1012
#define IDC_STATIC_B                    1012
#define IDC_SLIDER_C33                  1012
#define IDC_EDIT_COEF_A4                1012
#define IDC_CHECK_BENHANCE              1013
#define IDC_STATIC_BVALUE               1013
#define IDC_SLIDER_C32                  1013
#define IDC_CHECK_GAMMA2                1013
#define IDC_CHECK_SATURATIOn            1014
#define IDC_SLIDER_IHIGH                1014
#define IDC_EDIT_YREF                   1014
#define IDC_CHECK_GAMMA3                1014
#define IDC_CHECK_SPECIAL               1015
#define IDC_EDIT_COEF_A0                1015
#define IDC_EDIT_COEF_B0                1016
#define IDC_EDIT_COEF_C0                1017
#define IDC_EDIT_COEF_A1                1018
#define IDC_EDIT_COEF_B1                1019
#define IDC_EDIT_COEF_C1                1020
#define IDC_EDIT_COEF_A2                1021
#define IDC_EDIT_COEF_B2                1022
#define IDC_EDIT_COEF_C2                1023
#define IDC_EDIT_COEF_A3                1024
#define IDC_EDIT_COEF_B3                1025
#define IDC_EDIT_COEF_C3                1026
#define IDC_CHECK_D_ENABLE              1028
#define IDC_SLIDER_THRESOLD             1029
#define IDC_STATIC_THRESOLD_VAL         1030
#define IDC_SLIDER_KHIGH                1030
#define IDC_CHECK_RGBENABLE             1031
#define IDC_SLIDER_CHIGH                1031
#define IDC_CHECK_DFPENABLE             1032
#define IDC_SLIDER_CLOW                 1032
#define IDC_SLIDER_RGBFILTER            1033
#define IDC_STATIC_RGBF_VAL             1034
#define IDC_STATIC_DFPS_VAL             1035
#define IDC_SLIDER_DFP                  1036
#define IDC_CHECK_UVENABLE              1037
#define IDC_SLIDER_WBR                  1038
#define IDC_EDIT_COEF_B4                1038
#define IDC_SLIDER_WBG                  1039
#define IDC_EDIT_COEF_C4                1039
#define IDC_STATIC_RVAL                 1040
#define IDC_EDIT_COEF_A5                1040
#define IDC_STATIC_GVAL                 1041
#define IDC_CHECK_CC_ENABLE             1041
#define IDC_EDIT_COEF_B5                1041
#define IDC_SLIDER_WBB                  1042
#define IDC_EDIT_COEF_C6                1042
#define IDC_STATIC_BVAL                 1043
#define IDC_STATIC_C11_VAL              1043
#define IDC_EDIT_COEF_C5                1043
#define IDC_STATIC_C12_VAL              1044
#define IDC_EDIT_COEF_B7                1044
#define IDC_STATIC_C13_VAL              1045
#define IDC_EDIT_COEF_A6                1045
#define IDC_STATIC_C21_VAL              1046
#define IDC_EDIT_COEF_A7                1046
#define IDC_STATIC_C22_VAL              1047
#define IDC_EDIT_COEF_B6                1047
#define IDC_STATIC_C23_VAL              1048
#define IDC_EDIT_COEF_C7                1048
#define IDC_STATIC_C31_VAL              1049
#define IDC_EDIT_COEF_A8                1049
#define IDC_STATIC_C32_VAL              1050
#define IDC_EDIT_COEF_B8                1050
#define IDC_STATIC_C33_VAL              1051
#define IDC_STATIC_ILOW_VAL             1052
#define IDC_STATIC_IHIGH_VAL            1053
#define IDC_CHECK_S_ENABLE              1054
#define IDC_SLIDER_KLOW                 1055
#define IDC_STATIC_KLOW_VAL             1056
#define IDC_SLIDER_KREG                 1056
#define IDC_STATIC_KHIGH_VAL            1057
#define IDC_CHECK_BRI_ENABLE            1057
#define IDC_STATIC_CLOW_VAL             1058
#define IDC_EDIT_COEF_C8                1058
#define IDC_STATIC_CHIGH_VAL            1059
#define IDC_SLIDER_THRE                 1059
#define IDC_EDIT_COEF_A9                1059
#define IDC_STATIC_THRE_VAL             1060
#define IDC_SLIDER_COEFA_THRE           1060
#define IDC_EDIT_COEF_B9                1060
#define IDC_STATIC_KREG_VAL             1061
#define IDC_SLIDER_COEFB_THRE           1061
#define IDC_EDIT_COEF_C9                1061
#define IDC_STATIC_GAIN_VAL             1062
#define IDC_EDIT_RANGE1                 1062
#define IDC_CHECK_YUVE_ENABLE           1063
#define IDC_EDIT_RANGE5                 1063
#define IDC_CHECK_SOLAR_ENABLE          1064
#define IDC_EDIT_RANGE2                 1064
#define IDC_SLIDER_UCOEFB_THRE          1065
#define IDC_EDIT_RANGE7                 1065
#define IDC_SLIDER_VCOEFA_THRE          1066
#define IDC_EDIT_RANGE3                 1066
#define IDC_SLIDER_VCOEFB_THRE          1067
#define IDC_EDIT_RANGE6                 1067
#define IDC_SLIDER_SOLAR_THRE           1068
#define IDC_EDIT_RANGE4                 1068
#define IDC_SLIDER_UCOEFA_THRE          1069
#define IDC_SLIDER_RLOW                 1069
#define IDC_EDIT_RANGE8                 1069
#define IDC_STATIC_SOLAR_VAL            1070
#define IDC_SLIDER_GHIGH                1070
#define IDC_EDIT_RANGE9                 1070
#define IDC_STATIC_COEFA_VAL            1071
#define IDC_CHECK_AWB_ENABLE            1071
#define IDC_EDIT_RANGE0                 1071
#define IDC_STATIC_COEFB_VAL            1072
#define IDC_SLIDER_GLOW                 1072
#define IDC_STATIC_UCOEFA_VAL           1073
#define IDC_SLIDER_BHIGH                1073
#define IDC_STATIC_UCOEFB_VAL           1074
#define IDC_SLIDER_BLOW                 1074
#define IDC_STATIC_VCOEFA_VAL           1075
#define IDC_SLIDER_RGBHIGH              1075
#define IDC_STATIC_VCOEFB_VAL           1076
#define IDC_SLIDER_RGBLOW               1076
#define IDC_SLIDER_GRHIGH               1077
#define IDC_SLIDER_GRLOW                1078
#define IDC_SLIDER_GBHIGH               1079
#define IDC_SLIDER_GBLOW                1080
#define IDC_SLIDER_RHIGH                1081
#define IDC_STATIC_RH_VAL               1082
#define IDC_STATIC_RL_VAL               1083
#define IDC_STATIC_GH_VAL               1084
#define IDC_STATIC_GL_VAL               1085
#define IDC_STATIC_BH_VAL               1086
#define IDC_STATIC_BL_VAL               1087
#define IDC_STATIC_RGBH_VAL             1088
#define IDC_STATIC_RGBL_VAL             1089
#define IDC_STATIC_GRH_VAL              1090
#define IDC_STATIC_GRL_VAL              1091
#define IDC_STATIC_GBL_VAL              1092
#define IDC_STATIC_GBH_VAL              1093
#define IDC_STATIC_TR_VAL               1094
#define IDC_STATIC_TG_VAL               1095
#define IDC_SLIDER_GAIN                 1095
#define IDC_STATIC_TB_VAL               1096
#define IDC_SLIDER_C11                  1096
#define IDC_STATIC_COORD1               1098
#define IDC_STATIC_COORD2               1099
#define IDC_STATIC_AVERAGE              1099
#define IDC_STATIC_COORD3               1100
#define IDC_STATIC_WARP                 1100
#define IDC_STATIC_AVERAGE_VAL          1101
#define IDC_EDIT_REFISTERS              1101
#define IDC_STATIC_COORD4               1101
#define IDC_STATIC_WARP_VAL             1102
#define IDC_STATIC_GB                   1102
#define IDC_STATIC_COORD5               1102
#define IDC_STATIC_GR                   1103
#define IDC_STATIC_X                    1105
#define IDC_STATIC_Y                    1106
#define IDC_COMBO1                      1107
#define ID_SEARCH_DEVICE                32771
#define ID_IMAGECALCTYPE_NOM            32772
#define ID_IMAGECALCTYPE_log            32773
#define ID_IMAGECALCTYPE_NORMAL         32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
