# sensor 
obj-$(CONFIG_SENSOR_GC0308)   += camera_gc0308.o 
obj-$(CONFIG_SENSOR_OV2643)   += camera_ov2643.o
obj-$(CONFIG_SENSOR_OV7725)   += camera_ov7725.o
obj-$(CONFIG_SENSOR_HM1375)   += camera_hm1375.o
obj-$(CONFIG_SENSOR_OV9712)   += camera_ov9712.o
obj-$(CONFIG_SENSOR_OV2710)   += camera_ov2710.o
obj-$(CONFIG_SENSOR_AR0130)   += camera_ar0130.o
obj-$(CONFIG_SENSOR_H22)	  += camera_h22.o
obj-$(CONFIG_SENSOR_NT99141)+= camera_nt99141.o

# wrap sensor 
obj-$(CONFIG_LINUX_AKSENSOR)   += wrap_sensor.o aksensor.o
