#
# Since version 1.6 the asynchronous mode has been
# disabled by default. To re-enable it uncomment the
# corresponding CFLAG.
#

cryptodev-objs = crypto_run.o cryptdev.o cryptlib.o authenc.o zc.o util.o

obj-y += cryptodev.o

